name: Generate JaCoCo Badge
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  jacoco-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build plugin
        run: ./gradlew buildPlugin

      - name: Generate JaCoCo badge
        uses: cicirello/jacoco-badge-generator@v2.12.0
        with:
          generate-coverage-badge: true
          generate-branches-badge: true
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv

      - name: Commit and push badges
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            .github/badges/coverage.svg
            .github/badges/branches.svg
          commit-msg: "chore: update JaCoCo badges [skip ci]"
          github-token: ${{ secrets.GH_PAT }}

